# Generated by Django 4.2 on 2023-05-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a series genre', max_length=50, unique=True, verbose_name='Genre')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Seriál',
                'ordering': ['name'],
            },
        ),
    ]
