# Generated by Django 4.2 on 2023-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter first name', max_length=50, verbose_name='First name')),
                ('sname', models.CharField(help_text='Enter second name', max_length=50, verbose_name='Second name')),
                ('bio', models.TextField(blank=True, help_text='Enter bio', max_length=2000, null=True, verbose_name='Bio')),
                ('birth', models.DateField(blank=True, help_text='Enter date of birth', null=True, verbose_name='Date of birth')),
                ('foto', models.ImageField(blank=True, help_text='Select picture', null=True, upload_to='', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Director',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Enter description', null=True, verbose_name='description')),
                ('length', models.TimeField(blank=True, help_text='Enter length of this series', null=True, verbose_name='length')),
                ('season', models.IntegerField(blank=True, default=0, help_text='Enter number of seasons', null=True, verbose_name='Number of seasons')),
                ('episodes', models.IntegerField(blank=True, default=0, help_text='Enter number of episodes', null=True, verbose_name='Number of episodes')),
            ],
            options={
                'verbose_name': 'Series',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description', null=True, verbose_name='description'),
        ),
    ]
