# Generated by Django 4.2 on 2023-05-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_director_series_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='directors',
            field=models.ManyToManyField(to='series.director', verbose_name='Directors'),
        ),
        migrations.AddField(
            model_name='series',
            name='genres',
            field=models.ManyToManyField(to='series.genre', verbose_name='Genres of series'),
        ),
    ]
