# Generated by Django 4.2 on 2023-05-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_series_directors_series_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='length',
            field=models.IntegerField(blank=True, help_text='Enter length of this series in hours', null=True, verbose_name='length in hours'),
        ),
    ]
