# Generated by Django 4.2 on 2023-06-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_alter_series_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='foto',
            field=models.ImageField(blank=True, help_text='Select picture', null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
