# Generated by Django 4.2 on 2023-06-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_series_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
    ]
